# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab586c6fe9aff7ad9e307862b82f37babae7e6611c1ae2734ab6b410d8691a21eaf1a94519a9c4e3523fd61a566d7d1048f1e399b56a544916782e29961d3abd

test:
  secret_key_base: 984b70d7fa43ddda84976f4ccd0650933a2d3a97f020d1623ba221b21737046aee9ffcfc2be7182d6803090e8ffdae71db111077309762f5d55002fd68370858

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
